AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  SuggestExtensions:
    rubocop-rake: true
    rubocop-rspec: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
