AllCops:
  TargetRubyVersion: 2.7.7
  NewCops: enable
  SuggestExtensions:
    rubocop-rake: true
    rubocop-rspec: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Lint/EmptyBlock:
  Exclude:
    - spec/**/*_spec.rb

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Max: 30
